spring:
  application:
    name: post-service

  datasource:
    url: jdbc:h2:mem:post_db
    username: sa
    password: secret
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080
